name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build
        run: |
          # 创建 build 目录
          mkdir -p build
          # 复制所有网站文件到 build 目录
          cp -r *.html *.css *.js *.ico *.png *.jpg *.svg *.json *.txt build/ 2>/dev/null || true
          # 如果没有 index.html，创建一个简单的首页
          if [ ! -f "build/index.html" ]; then
            echo "<!DOCTYPE html><html><head><title>My Site</title></head><body><h1>Welcome to My Website</h1></body></html>" > build/index.html
          fi
          # 显示复制了哪些文件
          echo "Built files:"
          ls -la build/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
